name: 'Certificacao_Eng_Analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Certificacao_Eng_Analytics:  # Nome do projeto
    staging:  # Modelo de staging
      schema: staging
    sap_adventure_works:  # Modelo de tabela
      materialized: table
      schema: marts
