sources:
  - name: sap_adw
    description: Fonte do ERP da Adventur Works
    database: equatorial
    schema: sap_adw
    tables:
      - name: person
        columns:
          - name: BUSINESSENTITYID
            tests:
              - unique
              - not_null
                     
      - name: customer
        columns:
          - name: CUSTOMERID
            tests:
              - unique
              - not_null

      - name: salesreason
        columns:
          - name: SALESREASONID
            tests:
              - unique
              - not_null
              
      - name: salesorderheadersalesreason
        columns:
          - name: SALESORDERID
            tests:
              - not_null

      - name: employee
        columns:
          - name: BUSINESSENTITYID
            tests:
              - unique
              - not_null   

      - name: salesperson
        columns:
          - name: BUSINESSENTITYID
            tests:
              - unique
              - not_null  

      - name: stateprovince
        columns:
          - name: STATEPROVINCEID
            tests:
              - unique
              - not_null  

      - name: countryregion
        columns:
          - name: COUNTRYREGIONCODE
            tests:
              - unique
              - not_null  

      - name: address
        columns:
          - name: CITY
            tests:  
              - not_null
          - name: ADDRESSID
            tests:
              - unique
              - not_null 

      - name: creditcard
        columns:
          - name: CREDITCARDID
            tests:
              - unique
              - not_null 

      - name: salesorderheader
        columns:
          - name: SALESORDERID
            tests:
              - unique
              - not_null 

      - name: salesorderdetail
        columns:
          - name: SALESORDERID
            tests:  
              - not_null
          - name: SALESORDERDETAILID
            tests:
              - unique
              - not_null               

      - name: productcategory
        columns:
          - name: PRODUCTCATEGORYID
            tests:
              - unique
              - not_null 

      - name: productsubcategory
        columns:
          - name: PRODUCTCATEGORYID
            tests:  
              - not_null
          - name: PRODUCTSUBCATEGORYID
            tests:
              - unique
              - not_null 

      - name: product
        columns:
          - name: PRODUCTID
            tests:
              - unique
              - not_null 